import Head from "next/head";
import type { AppProps } from "next/app";
import "../styles/globals.css";
import { Layout } from "@components/layout/Layout";

export default function App({ Component, pageProps }: AppProps) {
    return (
        <main className="flex items-start">
            <Layout />
            <section className="bg-gray-50 min-h-screen w-full py-10 px-16 ml-60">
                <Head>
                    <title>Mweeter</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Component {...pageProps} />
            </section>
        </main>
    );
}
