import Head from "next/head";
import type { AppProps } from "next/app";
import { useRouter } from "next/router";
import clsx from "clsx";
import "../styles/globals.css";
import { AuthGuard } from "@components/guard/AuthGuard";
import { Layout } from "@components/layout/Layout";

export default function App({ Component, pageProps }: AppProps) {
    const { asPath } = useRouter();

    const isAuthenticated = !["/"].includes(asPath);
    const styles = clsx({
        ["py-20 md:py-10 px-8 md:px-16 ml-0 md:ml-60"]: isAuthenticated,
    });

    return (
        <div>
            <AuthGuard>
                <main className="flex items-start">
                    {isAuthenticated && <Layout />}

                    <section
                        className={`bg-gray-50 min-h-screen w-full ${styles}`}
                    >
                        <Head>
                            <title>Mweeter</title>
                            <meta
                                name="description"
                                content="Generated by create next app"
                            />
                            <link rel="icon" href="/favicon.ico" />
                        </Head>

                        <Component {...pageProps} />
                    </section>
                </main>
            </AuthGuard>
        </div>
    );
}
