import Head from "next/head";
import Image from "next/image";
import { HomePage } from "@views/HomePage";

export default function Home() {
    return (
        <div className="bg-gray-200 p-12 rounded-sm text-main-blue">
            <Head>
                <title>Mweeter</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <HomePage />
        </div>
    );
}
